<a href="https://colab.research.google.com/github/thanhsonopera/ML1/blob/main/Lecture_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

In [ ]:
# Hiển thị mô tả của các hàm trong numpy
np.info(np.ones, output=sys.stdout)

## Numpy cơ bản

In [ ]:
mylist = [1, 2, 3, 4]
x = np.array(mylist)
x

array([1, 2, 3, 4])

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Kiểu dữ liệu

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
x =np.array([1, 2, 3, 4], dtype=np.float)
x.dtype

<ipython-input-6-0f940a29e73f>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x =np.array([1, 2, 3, 4], dtype=np.float)


dtype('float64')

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}])

In [ ]:
d.dtype

dtype('O')

## Dimensions and shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim

3

In [ ]:
B.size

12

Nếu shape không đồng nhất, numpy sẽ hiểu đây là các object

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<ipython-input-11-39b57e6bbad9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0]), type(C[1])

(list, list)

## Truy vấn ma trận

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
A.shape

(3, 3)

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

Làm việc với các chiều trong ma trận, sẽ thông qua dấu ","

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.array([10, 10, 10]).shape)
print(A[1].shape)

(3,)
(3,)


In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Thống kê

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a = a + 100
a

array([100, 101, 102, 103])

In [ ]:
a = np.arange(4)
a

In [ ]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([110, 111, 112, 113])

In [ ]:
a * b

array([1000, 1010, 1020, 1030])

## Các phép toán ma trận

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
A.shape

(3, 3)

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])
B.shape

(3, 2)

In [ ]:
# nhân ma trận
C = A.dot(B)
C.shape,C

((3, 2),
 array([[20, 14],
        [56, 41],
        [92, 68]]))

In [ ]:
# nhân ma trận
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
# nghịch đảo
B.T

(2, 3)

In [ ]:
A = np.random.rand(1,3,128,256)
B = np.random.rand(1,3,256,128)
A.shape, B.shape

((1, 3, 128, 256), (1, 3, 256, 128))

In [ ]:
C = np.matmul(A,B)
C.shape

(1, 3, 128, 128)

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
A.shape, B.shape

((3, 3), (3, 2))

In [ ]:
# concatenate
C = np.concatenate([A, B], axis=1)
C.shape

(3, 5)

### And performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.06 ms, sys: 279 µs, total: 1.34 ms
Wall time: 701 µs


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 36.1 ms, sys: 0 ns, total: 36.1 ms
Wall time: 35.5 ms


333328333350000

## Boolean arrays
_(Also called masks)_

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))
A

array([[88, 17, 55],
       [24, 60, 62],
       [73, 56, 47]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([88, 55, 60, 73, 47])

In [ ]:
A > 30

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
A[A > 30]

array([88, 55, 60, 62, 73, 56, 47])

## Useful Numpy functions

### `random`

In [ ]:
np.random.random(size=2)

array([0.40809184, 0.5304859 ])

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

array([[0.55008204, 0.1967548 , 0.26073391, 0.08411892],
       [0.26596091, 0.82348629, 0.05119169, 0.9229238 ]])

---
### `arange`

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

---
### `reshape`

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

---
### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

---
### `identity`

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Exercises

1. Create a numpy array of size 10, filled with zeros.

In [3]:
import numpy as np
arr = np.zeros(10)
print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Create a numpy array with values ranging from 10 to 49

In [4]:
import numpy as np

arr = np.arange(10, 50)

print(arr)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
import numpy as np

matrix = np.ones((2, 2), dtype=int)

print(matrix)


[[1 1]
 [1 1]]


4. Create a numpy matrix of 3*2 float numbers, filled with ones.

In [7]:
import numpy as np

matrix = np.ones((3, 2), dtype=float)

print(matrix)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


5. Given the X numpy array, create a new numpy array with the same shape as X, filled with ones.

In [10]:
import numpy as np
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
arr = np.ones_like(X)

print(arr)
# your code goes here


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


6. Create a numpy matrix of 4*4 integers, filled with fives.

In [9]:
import numpy as np

matrix = np.full((4, 4), 5, dtype=int)

print(matrix)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


7. Create a 3x3x3 numpy matrix, filled with random float values.

In [11]:
import numpy as np

matrix= np.random.rand(3, 3, 3)

print(matrix)


[[[0.71360021 0.43809856 0.74675265]
  [0.84449103 0.14003517 0.41891804]
  [0.79942755 0.4500096  0.63202724]]

 [[0.90846248 0.76125005 0.79135789]
  [0.47949694 0.63135887 0.60247068]
  [0.12502813 0.73479972 0.68603429]]

 [[0.3305815  0.75537625 0.28924545]
  [0.69326961 0.61149518 0.23208896]
  [0.39097348 0.2557979  0.83666585]]]


8. Given the X python list convert it to an Y numpy array

In [12]:
import numpy as np
X = [1, 2, 3]
Y = np.array(X)
print(Y)
# your code goes here


[1 2 3]


Given the X numpy array, show it's first three elements

In [13]:
import numpy as np
X = np.array(['A','B','C','D','E'])
res = X[:3]
print(res)
# your code goes here


['A' 'B' 'C']


9. Given the X numpy matrix, show the first row elements

In [14]:
import numpy as np
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
res = X[0, :]

print(res)
# your code goes here


[1 2 3 4]


10. Given the X numpy matrix, show the last row elements

In [15]:
import numpy as np
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
res = X[-1, :]

print(res)
# your code goes here


[13 14 15 16]


11. Given the X numpy matrix, show the last element on last row

In [16]:
import numpy as np
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
res = X[-1, :]

print(res[-1])


16


12. Given the X numpy matrix, show the first two elements on the first two rows

In [18]:
import numpy as np
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(X[:2, :2])
# your code goes here


[[1 2]
 [5 6]]


13. Loss function: Mean Square Error (MSE)

Mean square error (MSE) is calculated as the average of the square of the difference between predictions and actual observations. Mathematically we can represent it as follows :

![](https://journaldev.nyc3.digitaloceanspaces.com/2020/12/Mean-square-error.png)

In [23]:
act = np.array([1.1, 2, 1.7])
pred = np.array([1, 1.7, 1.5])
res = np.mean((act - pred) ** 2)
print(res)
# your code goes here


0.04666666666666667


14. Mean Absolute Error (MAE)

Mean Absolute Error (MAE) is calculated as the average of the absolute difference between predictions and actual observations. Mathematically we can represent it as follows :

![](https://journaldev.nyc3.digitaloceanspaces.com/2020/12/MAE.gif)

In [22]:
batchsize = 1
channel =3
H = 128
W = 128
act = np.random.rand(batchsize, channel, H, W)
pred = np.random.rand(batchsize, channel, H, W)
res = np.mean(np.abs(act - pred))
print(res)
# your code goes here


0.3327209872369141
